name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Noje.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build storybook
        run: npm run build-storybook

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Publish Storybook on Chromatic
          uses: chromaui/action@v1
          with:
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
            token: ${{ secrets.GITHUB_TOKEN }}
